name: fma
description: "Free Music App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # core
  flutter_riverpod: ^2.4.9
  hive: ^2.2.3
  # network
  cached_network_image: ^3.3.1
  # auido
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  just_audio_background: ^0.0.1-beta.11
  # ui
  iconsax: ^0.0.8
  flex_color_scheme: ^7.3.1
  cupertino_icons: ^1.0.2

  op_package:
    git:
      url: https://github.com/opiasdream/op_package.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
